### ISSUE TITLE
which ROS does this plugin work with?

### ISSUE THREAD

**Issue by jih189** [ahmad-aljabali/ROS-Blender-Addon#3]
I have tried this plugin with ROS melodic. It looks like that it does not work.

**Comment by emplant2000** [comment]
FYI
https://bit.ly/3MJE2k0

running wiht roscore and UPBGE and just run as [p]lay

**Comment by jih189** [comment]
Thanks for reply. I am not familiar with UPBGE. Could you give some tutorial in README about how to use UPBGE here in the README?

**Comment by emplant2000** [comment]
pls just join facebook as bit.ly URL at first.

it require UPBGE.
https://upbge.org/#/

import a script and push [p]lay as ok.

**Comment by jih189** [comment]
The main problem I have now is that I can't enable the add-on. Here is the error:
Traceback (most recent call last):
  File "/root/Blender/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/root/.config/blender/3.4/scripts/addons/ROS_addon/__init__.py", line 14, in <module>
    from ROS_addon.ROS_OT_run import ROS_OT_run
  File "/root/.config/blender/3.4/scripts/addons/ROS_addon/ROS_OT_run.py", line 6, in <module>
    from ROS_addon.external.geometry_msgs.msg import Point, Quaternion, Pose
  File "/root/.config/blender/3.4/scripts/addons/ROS_addon/external/geometry_msgs/msg/__init__.py", line 1, in <module>
    from ._Accel import *
  File "/root/.config/blender/3.4/scripts/addons/ROS_addon/external/geometry_msgs/msg/_Accel.py", line 5, in <module>
    import genpy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by jih189** [comment]
I found the solution. The problem is caused by the python in blender does not have the rospy. AND you have to install them manually by go to blender's python(it should be in Blender/3.x/python/bin/python3.x).
1. cd Blender/3.x/python/bin/python3.x
2. ./python3.x -m ensurepip
3. ./python3.x -m pip install pyyaml rospkg opencv-python

**Comment by jih189** [comment]
is it normal that it is extremely slow?
